<?php

$params = array();
$srv = null;
foreach($info['records'] as $rec)
{
	if(!isset($rec['type'])) continue;
	if($rec['type'] == 'TXT')
	{
		$px = array();
		$plist = explode(' ', $rec['txt']);
		foreach($plist as $p)
		{
			$p = trim($p);
			if(!strlen($p)) continue;
			$kv = explode('=', $p, 2);
			if(count($kv) != 2) continue;
			$px[$kv[0]] = $kv[1];
		}
		if(isset($px['txtvers']))
		{
			$params = $px;
		}
	}
	else if($rec['type'] == 'SRV')
	{
		$srv = $rec;
	}
}
if(count($params) && is_array($srv) && isset($params['txtvers']) && $params['txtvers'] == 1 && isset($params['path']) && strlen($params['path']))
{
	echo "\t\t\t" . '<form method="post" action="' . htmlspecialchars($query_string, ENT_QUOTES, 'UTF-8') . '">' . "\n";
	echo "\t\t\t\t" . '<dl>' . "\n";
	echo "\t\t\t\t\t" . '<dt><label for="uris">Enter query URIs, one per line:</label></dt>' . "\n";
	echo "\t\t\t\t\t" . '<dd><textarea name="bm:uris" id="uris" cols="60" rows="8">' . htmlspecialchars($fields['bm:uris']) . '</textarea></dd>' . "\n";
	echo "\t\t\t\t" . '</dd>' . "\n";
	echo "\t\t\t\t" . '<input type="submit" name="bm:go" value="Query">' . "\n";	
	echo "\t\t\t" . '</form>' . "\n";
	if(!empty($_POST['bm:go']))
	{
		echo "\t\t\t" . '<ul>';
		echo "\t\t\t\t" . '<li>Connecting to <code>http://' . $srv['target'] . ':' . $srv['port'] . '</code></li>';
		$ch = curl_init('http://' . $srv['target'] . ':' . $srv['port']);
		echo "\t\t\t\t" . '<li>Setting <code>Host</code> to <code>' . $fqdn . '</code></li>' . "\n";
		curl_setopt($ch, CURLOPT_HTTPHEADER, array('Host: ' . $fqdn));
		$path = $params['path'];
		if(substr($path, 0, 1) != '/') $path = '/' . $path;
		$path .= (strpos('?', $path) === false ? '?' : '&');
		$uri = explode(' ', str_replace("\n", ' ', $fields['bm:uris']));
		foreach($uri as $u)
		{
			$u = trim($u);
			if(!strlen($u)) continue;
			$path .= 'uri[]=' . urlencode($u) . '&';
		}
		echo "\t\t\t\t" . '<li>Requesting <code>' . htmlspecialchars($path, ENT_NOQUOTES, 'UTF-8') . '</code></li>' . "\n";
		curl_setopt($ch, CURLOPT_URL, 'http://' . $srv['target'] . ':' . $srv['port'] . $path);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($ch, CURLOPT_HEADER, true);
		curl_setopt($ch, CURLOPT_NOBODY, true);						
		echo "\t\t\t" . '</ul>';
		@flush();
		if(false === ($r = curl_exec($ch)))
		{
			echo "\t\t\t" . '<p>' . htmlspecialchars(curl_error($ch)) . '</p>' . "\n";
		}
		else
		{
			$info = curl_getinfo($ch);
			echo "\t\t\t" . '<p><code>' . str_replace("\n", '<br>', htmlspecialchars($r)) . '</code></p>' . "\n";
		}

	}
}
else
{
	echo "\t\t\t" . '<ul>';
	if(count($params))
	{
		if(isset($params['txtvers']))
		{
			if($params['txtvers'] != 1)
			{
				echo "\t\t\t\t" . '<li>TXT record txtvers value is invalid (should be 1)</li>' . "\n";
			}
		}
		else
		{
			echo "\t\t\t\t" . '<li>TXT record txtvers value is missing</li>' . "\n";
		}
	}
	echo "\t\t\t" . '</ul>';
}
