		<form method="get" action="">
			<h2>DAB Digital Radio</h2>
			<input type="hidden" name="kind" value="dab">
			<?php	
			Form::input('ecc', 'Extended Country Code:');
			Form::input('eid', 'Ensemble Identifier:');
			Form::input('sid', 'Service Identifier:');
			Form::input('scids', 'Service Component Identifier:');
			?>
			<p>
				If the service is delivered via X-PAD, you need to specify the
				Application Type and User Application type.
			</p>
			<?php
			Form::input('appty', 'X-PAD Application Type:');
			Form::input('uatype', 'User Application Type:');
			?>
			<p>
				Alternately, if the audio is delivered as data in an Independent
				Service Component, specify the Packet Address:
			</p>
			<?php
			Form::input('pa', 'Packet Address:');
			?>
			<input type="submit" value="Go">
		</form>
