<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>TVDNS/RadioDNS Lookup Tool</title>
		<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.7.0/build/reset/reset-min.css"> 
		<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.7.0/build/base/base-min.css"> 
		<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.7.0/build/fonts/fonts-min.css"> 
		<link rel="stylesheet" type="text/css" href="http://projectbaird.com/screen.css" media="screen"> 
		<link rel="stylesheet" type="text/css" href="http://projectbaird.com/print.css" media="print"> 
		<style type="text/css">
hr { display: none; }
p.code-block { background: #eee; margin: 0; padding: 8px; line-height: 1.5em; }
p.code-block code { display: inline; white-space: pre; color: #700; }
		</style>
	</head>
	<body class="toys lookup">
		<div id="surround">
			<h1><a href="/lookup/">TVDNS/RadioDNS Lookup Tool</a></h1>
			<?php Form::alerts();

if(strlen($fqdn))
{
?>
		<div class="section results">
			<h2>Lookup results</h2>
			<p>Fully-qualified domain name: <code><?php e($fqdn); ?></code></p>
			
			<?php
			if(strlen($svc))
			{
			?>
			<p>Service URI: <code><?php e($svc); ?></code></p>
			<?php			
			}
			?>

			<?php
			if($discovery)
			{
			?>
			<p>Service-discovery target: <code><?php e($discovery->target); ?></code></p>
			<?php			
			}
			?>
	<?php			
	if(!$discovery || !count($discovery->discovered))
	{
		echo "\t\t\t" . '<p>No known services discovered.</p>' . "\n";
	}
	echo "\t\t" . '</div>' . "\n";

	if($discovery && count($discovery->discovered))
	{
		require_once(dirname(__FILE__) . '/discovery.phtml');
	}
	echo "\t\t" . '<hr>' . "\n";
}

		?>
		<?php if(!strlen($fqdn) || $fields['kind'] == 'ip')
		{
		?><div class="section">
		<?php require_once(dirname(__FILE__) . '/ipstream.phtml'); ?>
		</div>
		<hr>
		<?php
		}
		
		if(!strlen($fqdn) || $fields['kind'] == 'dvb')
		{		
		?><div class="section">
		<?php require_once(dirname(__FILE__) . '/dvb.phtml'); ?>
		</div>
		<hr>
		<?php
		}
		
		if(!strlen($fqdn) || $fields['kind'] == 'fm')
		{		
		?><div class="section">
		<?php require_once(dirname(__FILE__) . '/fm.phtml'); ?>
		</div>
		<hr>
		<?php
		}
		
		
		if(!strlen($fqdn) || $fields['kind'] == 'dab')
		{		
		?><div class="section">
		<?php require_once(dirname(__FILE__) . '/dab.phtml'); ?>
		</div>
		<hr>
		<?php
		}
		
		if(!strlen($fqdn) || $fields['kind'] == 'drm' || $fields['kind'] == 'amss')
		{		
		?>
		<div class="section">
		<?php require_once(dirname(__FILE__) . '/drm-amss.phtml'); ?>
		</div>
		<hr>
		<?php
		}
		?>
		<div id="footer"> 
			<p>Copyright © 2009-2010. Dèanta ann an Alba.</p> 
		</div> 		
		<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-9096696-3");
pageTracker._trackPageview();
} catch(err) {}</script>
	</body>
</html>
