			<div class="section channel-list">
				<table class="lineup">
					<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">Name</th>
							<th scope="col">Kind</th>
							<th scope="col">Class</th>
							<th scope="col">CA</th>
							<th scope="col">Audio</th>
							<th scope="col">EPG</th>
							<th scope="col">Target</th>
							<th scope="col">RadioEPG</th>
							<th scope="col">RadioVIS</th>
							<th scope="col">RadioTAG</th>
							<th scope="col">Website</th>
							<th scope="col">Resolver</th>
							<th scope="col">XRD</th>
							<th scope="col">Sources</th>
						</tr>
					</thead>
					<tbody>
<?php
$channels = $listing->channels();
foreach($channels as $num => $info)
{
	$class = implode(' ', array(
		'service',
		$info->kind,
		$info->serviceClass,
		$info->ca ? 'ca' : 'fta',
		$info->data ? 'data' : ($info->audio ? 'audio' : 'video'),
		));
?>
						<tr class="<?php e($class); ?>">
<?php
echo '<th scope="row">' . $info->lcn . '</th>';
echo '<td class="name"><a href="' . _e($info->lookupURL) . '">';
if(isset($info->depiction[0]))
{
	echo '<img src="' . _e($info->depiction[0]->href) . '" style="max-height: 100px;"><br>';
}
echo  _e($info->displayName) . '</a></td>';
echo '<td class="kind">' . _e($platform[$info->kind]['shortName']). '</td>';
echo '<td class="serviceClass">' . _e($info->serviceClass) . (!strlen($info->lcn) ? ' [Alternative variant]': null) . '</td>';
echo '<td class="encrypted">' . (!empty($info->ca) ? 'Yes' : '&nbsp;') . '</td>';
echo '<td class="audio">' . (!empty($info->audio) ? 'Yes' : '&nbsp;') . '</td>';
echo '<td class="epg">' . (!empty($info->hasOtaEpg) ? 'OTA' : '&nbsp;') . '</td>';
if($info->rdns)
{
	echo '<td class="target"><abbr title="' . _e($info->rdns->target) . '">…</abbr></td>';
}
else
{
	echo '<td class="target">&nbsp;</td>';
}
echo '<td class="radioepg">' . (isset($info->services['_radioepg._tcp']) ? 'Yes' : '&nbsp;') . '</td>';
echo '<td class="radiovis">' . (isset($info->services['_radiovis._tcp']) ? 'Yes' : '&nbsp;') . '</td>';
echo '<td class="radiotag">' . (isset($info->services['_radiotag._tcp']) ? 'Yes' : '&nbsp;') . '</td>';
if(isset($info->services['_http._tcp']))
{
	echo '<td class="website"><a href="' . _e($info->services['_http._tcp']['uri']) . '" title="' . _e($info->services['_http._tcp']['uri']) . '">…</a></td>';
}
else
{
	echo '<td class="website">&nbsp;</td>';
}
if(isset($info->services['_broadcast-meta._tcp']))
{
	echo '<td class="resolver"><a href="' . _e($info->lookupURL) . '">Yes</a></td>';
}
else
{
	echo '<td class="resolver">&nbsp;</td>';
}
echo '<td class="xrd">' . (isset($info->services['_xrd._tcp']) ? 'Yes' : '&nbsp;') . '</td>';

if(isset($info->sources))
{
	echo '<td class="streams">';
	$list = array();
	foreach($info->sources as $source)
	{
		$list[] = '<a href="' . _e($source['href']) . '">' . _e($source['type']) . '</a> (' . $source['media'] . (isset($source['proto']) ? ';' . $source['proto'] : null) . (strlen($source['delivery']) ? '; ' . $source['delivery'] : null) . ')';
	}
	echo implode('<br>', $list);
	echo '</td>';
}
else
{
	echo '<td class="streams">&nbsp;</td>';
}

?>
						</tr>
<?php
}
?>
					</tbody>
				</table>
			</div>
