<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Boxify</title>
		<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.7.0/build/reset/reset-min.css"> 
		<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.7.0/build/base/base-min.css"> 
		<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.7.0/build/fonts/fonts-min.css"> 
		<link rel="stylesheet" type="text/css" href="http://projectbaird.com/screen.css" media="screen"> 
		<link rel="stylesheet" type="text/css" href="http://projectbaird.com/print.css" media="print"> 
	</head>
	<body class="toys boxify">
		<div id="surround">
			<h1><a href="/boxify/">Boxify</a></h1>		
<?php if($kind) { ?>
			<div class="section">
			<p>Selected network:
			<strong><?php
			echo _e($platform[$kind]['name']) . ' → ' . _e($platform[$kind]['onid'][$onid]['name']) . ' → ' . _e($platform[$kind]['onid'][$onid]['nid'][$nid]['name']);
			?></strong>
			</p>
			<?php
			if(empty($_REQUEST['xrd']) && count($xrd))
			{
				echo '<p><strong>One or more XRD sources were discovered.</strong> <a href="' . _e($query_string . '&xrd=1') . '">Retry request with XRD processing enabled</a>. This will update/augment the channel line-up.</p>';
			}
			?>
			<h2>What is it?</h2>
			<p>
				This prototype uses static channel data intended to match that which would be
				obtained by a receiver. It arranges a channel listing in the same way a
				device would, and then performs service discovery on each of the available
				broadcast services.
			</p>
			<h2>Why?</h2>
			<p>
				The idea is to demonstrate two things: first, how a hybrid receiver can provide
				additional services through lightweight protocols for service discovery; second,
				to show information capable of being utilised by a "second screen" device which
				doesn't itself contain a receiver.
			</p>
			<h2>How does it work?</h2>
			<p>
				We start with a static list of services - this is a dump from a MythTV channel
				database, and is the same information that any DVB-T receiver has access to. The
				tool immediately performs DNS lookups (using <a href="http://projectbaird.com/discovery/tvdns/">TVDNS</a>)
				to find advertised IP-delivered services relating to the channels in the line-up.
			</p>
			<p>
				If one of the services advertised in DNS is <code>_xrd._tcp</code>, this tool will
				optionally retrieve it and process it. XRD documents allow both existing
				channel data to be updated with extra information (such as channel logos
				and more descriptive names, and links to simulcast streams), as well
				as additional channels, be they linear or or-demand.
			</p>
			<p>
				Each channel name is a link to the <a href="/lookup/">lookup tool</a> page for that
				specific channel.
			</p>
			<p>
				Channels which are solely IP-delivered (i.e., described by the XRD, have some kind
				of available stream, and aren't already in the line-up) are given channel numbers
				in the range 900-999.
			</p>
			<p>
				The <em>only</em> pieces of static data here is the MythTV dump (which should match
				what a real live DTT tuner sees in any case) and the <code>tvdns.net</code> root
				domain for TVDNS lookups. Everything else is service discovery-driven.
			</p>
			</div>
			<div class="section">
				<table class="lineup">
					<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">Name</th>
							<th scope="col">Kind</th>
							<th scope="col">Service class</th>
							<th scope="col">Encrypted</th>
							<th scope="col">Audio-only</th>
							<th scope="col">OTA EPG</th>
							<th scope="col">Target</th>
							<th scope="col">RadioEPG</th>
							<th scope="col">RadioVIS</th>
							<th scope="col">Website</th>
							<th scope="col">Metadata resolver</th>
							<th scope="col">Streams</th>
						</tr>
					</thead>
					<tbody>
<?php
foreach($channels as $num => $info)
{
	$class = array('service');
	$class[] = $info['kind'];
	$class[] = $info['serviceClass'];
	$class[] = empty($info['encrypted']) ? 'fta' : 'ca';
	if(empty($info['data']))
	{
		$class[] = empty($info['audio']) ? 'video' : 'audio';
	}
	else
	{
		$class[] = 'data';
	}
	$class = implode(' ', $class);
?>
						<tr class="<?php e($class); ?>">
<?php
echo '<th scope="row">' . $info['lcn'] . '</th>';
echo '<td class="name"><a href="' . _e($info['lookup']) . '">';
if(isset($info['depiction']))
{
	echo '<img src="' . _e($info['depiction']) . '"><br>';
}
echo  _e($info['name']) . '</a></td>';
echo '<td class="kind">' . _e($platform[$info['kind']]['shortName']) . '</td>';
echo '<td class="serviceClass">' . _e($info['serviceClass']) . '</td>';
echo '<td class="encrypted">' . (!empty($info['encrypted']) ? 'Yes' : '&nbsp;') . '</td>';
echo '<td class="audio">' . (!empty($info['audio']) ? 'Yes' : '&nbsp;') . '</td>';
echo '<td class="ota-epg">' . (!empty($info['ota']) ? 'Yes' : '&nbsp;') . '</td>';
if($info['target'])
{
	echo '<td class="target"><a href="#target-' . ($info['targetIndex'] + 1) . '">' . ($info['targetIndex'] + 1) . '</a></td>';
}
else
{
	echo '<td class="target">&nbsp;</td>';
}
echo '<td class="radioepg"></td>';
echo '<td class="radiovis"></td>';
if(isset($info['website']))
{
	echo '<td class="website"><a href="' . _e($info['website']) . '">' . _e($info['websiteHost']) . '</a></td>';
}
else
{
	echo '<td class="website"></td>';
}
if(!empty($info['resolver']))
{
	echo '<td class="resolver"><a href="' . _e($info['lookup']) . '">Yes</a></td>';
}
else
{
	echo '<td class="resolver">&nbsp;</td>';
}
if(isset($info['streams']))
{
	echo '<td class="streams">';
	$list = array();
	foreach($info['streams'] as $info)
	{
		$list[] = '<a href="' . _e($info['href']) . '">' . _e($info['type']) . '</a>';
	}
	echo implode(', ', $list);
	echo '</td>';
}
else
{
	echo '<td class="streams">&nbsp;</td>';
}

?>
						</tr>
<?php
}
?>
					</tbody>
				</table>
			</div>
<?php }

$c = 0;
foreach($targets as $fqdn => $target)
{
	$c++;
?>
			<div class="section">
				<h2 id="target-<?php e($c); ?>">#<?php e($c); ?>: <code><?php e($fqdn); ?></code></h2>
<?php print_r($target); ?>
			</div>
<?php
}
 ?>
		</div>
		<div id="footer"> 
			<p>Copyright © 2009-2010. Dèanta ann an Alba.</p> 
		</div> 		
		<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-9096696-3");
pageTracker._trackPageview();
} catch(err) {}</script>
	</body>
</html>
