<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title><?php e($selectedChannel->displayName); ?></title>
		<link rel="stylesheet" href="ipad.css" media="screen">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-status-bar-style" content="black">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
		<link rel="apple-touch-icon" href="http://projectbaird.com/logo512.png" type="image/png">
	</head>
	<body>
		<div id="content">
			<h1><span class="c">On now</span></h1>
<?php

$depict = null;

foreach($selectedChannel->depiction as $d)
{
	if($d->height && $d->height < 35)
	{
		$depict = $d;
		break;
	}
}

if($depict)
{
	$style = "text-indent: -11000em; background-image: url('" . addslashes($depict->href) . "');";
	if($depict->preferredBackground)
	{
		$style .= ' background-color: ' . $depict->preferredBackground;
	}
	$style = ' style="' . $style . '"';
}
else
{
	$style = null;
}

?>
			
			<h2<?php echo $style; ?>><?php e($selectedChannel->displayName); ?></h2>
			<?php if($episode) { ?>
			<div class="now-playing">
				 <h3><?php e($page_title); ?></h3>
				<p>
<?php
if(strlen($episode->mediumSynopsis))
{					
	e($episode->mediumSynopsis);
}
else if(strlen($episode->longSynopsis))
{
	e($episode->longSynopsis);
}
?>
				</p>
<?php
$depiction = null;
if(isset($episode->depiction))
{
	$depiction = $episode->depiction;
}
else if(isset($series->depiction))
{
	$depiction = $series->depiction;
}
else if(isset($brand->depiction))
{
	$depiction = $brand->depiction;
}
if(strlen($depiction))
{
	echo '<p class="depiction"><img src="' . _e($depiction) . '" height="200" /></p>';
}
$url = $location;
if(isset($episode->microsite))
{
	$url = $episode->microsite;
}
?>
				<ul class="links">
					<li><a href="<?php e($url); ?>">Find out more</a></li>
				</ul>
				<?php } ?>
			</div>
			<div class="block">
				<h3>More like this</h3>
				<p>
					Some recommendations
				</p>
<?php
if(isset($subjects))
{
//	print_r($subjects);
}
?>
			</div>
			<div class="block">
				<h3>Coming up</h3>
				<p>
					I live for the future. Tell me what’s on next.
				</p>
			</div>
		</div>
		<div id="sidebar">
			<h2><span class="c">Living room TV</span></h2>
			<ul class="nav">
				<li class="active icon-tv"><a href="#">On now</a></li>
				<li class="icon-guide"><a href="#">Programme guide</a></li>
				<li class="icon-favourites"><a href="#">Favourites</a></li>
				<li class="icon-recommended"><a href="#">Recommendations</a></li>
			</ul>
<?php
if(count($applinks))
{
	echo '<h3>Would you like to know more?</h3>';
	echo '<dl class="nav">';
	foreach($applinks as $topic => $links)
	{
		if(count($links) == 1)
		{
			echo '<dt class="icon-tv"><a href="' . _e($links[0]['href']) . '" title="' . _e($links[0]['action']) . '">' . _e($links[0]['topic']) . '</a></dt>';
		}
		else
		{
			echo '<dt class="icon-tv">' . _e($links[0]['topic']) . '</dt>';
			foreach($links as $l)
			{
				echo '<dd><a href="' . _e($l['href']) . '" title="' . _e($l['action']) . '">' . _e($l['label']) . '</a></dd>';				
			}
		}
	}
	echo '</dl>';
}
?>
		</div>
		<span id="strip"></span>
	</body>
</html>